const config = {
  baseUrl: "https://travelde.pythonanywhere.com/travelapp", //for login signup
  // baseUrl1: "http://192.168.5.73:5226/api",// "company",
  //  baseUrl1: "http://25.29.194.32:5226/api" ,//"home"
  //http://www.medicalinsurance0000.somee.com/swagger/index.html
  // baseUrl1: "http://192.168.5.252:5226/api",
 baseUrl1: "http://www.medicalinsurancenew.somee.com/api",
  login: "login",
  engineers: "Engineers",
  cities: "Cities",
  hospitals: "Hospitals",
  engineeringedepars: "EngineeringeDepars",
  workplaces: "Workplaces",
  engineeringunits: "EngineeringUnits",
  surgicalprocedures: "SurgicalProcedures",
  annualdata: "AnnualData/CalculateAmount",
  persons: "Persons",
  searchByEnsurance: "Searchs/find/ByEnsuranceNumber",
  subscriber: "Subscriber/upload",
  claims: "Claims/upload",
  recovereds: "Recovereds",
  specializations: "Specializations",
  searchByEngUnits: "Searchs/find/EngUnits",
  searchByHospital: "Searchs/find/Hospital",
  relativeEng: "Quiries/engineer with HisFamily",
  annualSetting: "AnnualData/AnnualSetting",
  AnnualData: "AnnualData",
  cashExcel: "UploadSExcel/uploadCashExcel",
  retExcel: "UploadSExcel/uploadRetirementExcel",
  boxExcel: "UploadSExcel/uploadBoxExcel",
  searchByEng: "Searchs/find/ByEngNumber",
  searchByEncur: "Searchs/find/ByEnsuranceNumber",
  editEng: "update-Eng-details",
  searchByName: "Searchs/find/ByName",
  addClaim: "ClaimsExcel/AddClaim",
  searchByNational: "Searchs/find/Search-By-National-Id",
  searchBySub:"Searchs/find/BySubNumber",
  relationType: "AnnualData/GetRelationType",
  paymethod: "AnnualData/get-allPayMethode",
  notes: "Nots",
  putWordImage: "update-imagesAndWords",
  GetPayMethod: "AnnualData/GetPayMethodByEngineerId",
  GetBenifites: "AnnualData/GetEngineerStatus",
  GetBenifitesFamily: "AnnualData/GetFamilyMemberStatus",
  updateImageWord: "update-imagesAndWords",
  renewal: "AnnualData/RenewEngineerAnnualData",
  renewalPerson: "AnnualData/RenewFamilyMembersAnnualData",
  editPerson: "update-person-details",
  relationYear: "AnnualData/RelationType-With-Notes",
  relation: "AnnualData/GetRelationType",
  renewalQuiries: "Quiries/GetEngineerWithFamilyData",
};
export default config;
